/**
 * Inventory management data model definitions
 * Contains enums and interfaces enforcing strict frontend-backend data format
 * All fields aligned 1:1 with backend database structure
 */

/**
 * Inventory category enum
 * Restricts categories to fixed valid values to prevent invalid submissions
 */
export enum Category {
  Electronics = 'Electronics', // Electronics category
  Furniture = 'Furniture',     // Furniture category
  Clothing = 'Clothing',       // Clothing category
  Tools = 'Tools',             // Tools category
  Miscellaneous = 'Miscellaneous' // Miscellaneous category
}

/**
 * Inventory stock status enum
 * Indicates inventory availability status
 */
export enum StockStatus {
  InStock = 'In Stock',       // In stock / sufficient
  LowStock = 'Low Stock',     // Low stock
  OutOfStock = 'Out of Stock' // Out of stock
}

/**
 * Complete inventory item interface
 * Includes auto-increment primary key field, used for full item data from backend
 */
export interface InventoryItem {
  item_id: number;               // Primary key ID - auto-generated by backend, read-only on frontend
  item_name: string;             // Item name - required, globally unique (dual frontend-backend validation)
  category: Category;            // Item category - strictly follows Category enum
  quantity: number;              // Stock quantity - required, non-negative integer (frontend validation)
  price: number;                 // Item price - required, non-negative integer (frontend validation)
  supplier_name: string;         // Supplier name - required
  stock_status: StockStatus;     // Stock status - strictly follows StockStatus enum
  featured_item: 0 | 1;          // Featured flag - 0 = normal, 1 = featured, default 0
  special_note?: string | null;  // Special note - optional field, nullable
}

/**
 * Request body interface for create/update operations
 * Excludes backend-managed item_id field, used for POST/PUT requests
 */
export interface InventoryRequest {
  item_name: string;             // Item name - required, globally unique
  category: Category;            // Item category - enum type
  quantity: number;              // Stock quantity - non-negative integer
  price: number;                 // Item price - non-negative integer
  supplier_name: string;         // Supplier name - required
  stock_status: StockStatus;     // Stock status - enum type
  featured_item?: 0 | 1;         // Featured flag - optional, default 0
  special_note?: string | null;  // Special note - optional, nullable
}